import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>André Siqueira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <h1><span className={styles.hash}>#</span> André Siqueira </h1>
      <h2>Desenvolvedor Front-End</h2>
      </main>

      <footer className={styles.footer}>
        <ul>
          <li><a target='_blank' rel='noreferrer' href='https://github.com/andresiqueira'>Github</a></li>
          <li><a target='_blank' rel='noreferrer' href='https://www.linkedin.com/in/andre-siqueira'>Linkedin</a></li>
        </ul>
      </footer>
    </div>
  )
}
